### ISSUE TITLE
Exception in thread "main" org.apache.spark.SparkException: Task not serializable

### ISSUE THREAD

**Issue by Issac-Newton** [david-siqi-liu/sparklyclean#1]
hi,sorry to bother you. I met a problem when I **Compile and run GenerateLabeledPoints on the dataset**. 
The output as below:
hmBKV2RID:
BKV(2,hsw) -> List(22)
BKV(2,viclr) -> List(21)
BKV(2,bic) -> List(7)
.....
BKV(2,fa) -> List(26)
BKV(2,qlp) -> List(42)
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:345)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:335)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2299)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:797)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:796)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
        at org.apache.spark.rdd.RDD.mapPartitions(RDD.scala:796)
        at com.davidsiqiliu.sparklyclean.GenerateLabeledPoints$.main(GenerateLabeledPoints.scala:99)
        at com.davidsiqiliu.sparklyclean.GenerateLabeledPoints.main(GenerateLabeledPoints.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.NotSerializableException: com.davidsiqiliu.sparklyclean.GenerateLabeledPointsConf
Serialization stack:
        - object not serializable (class: com.davidsiqiliu.sparklyclean.GenerateLabeledPointsConf, value: com.davidsiqiliu.sparklyclean.GenerateLabeledPointsConf@58c42c8c)
        - field (class: com.davidsiqiliu.sparklyclean.GenerateLabeledPoints$$anonfun$9, name: args$1, type: class com.davidsiqiliu.sparklyclean.GenerateLabeledPointsConf)
        - object (class com.davidsiqiliu.sparklyclean.GenerateLabeledPoints$$anonfun$9, <function1>)
        at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:342)
        ... 21 more

I try to search solution from this, but I am not familiary with scala and spark. Hope can get your help. Thanks

**Comment by david-siqi-liu** [comment]
Thank you for the feedback. I have fixed the error. It was due to ScallofConf being not serializable in the `mapPartition` step. Please confirm and close the issue.

**Comment by Issac-Newton** [comment]
it works and thanks very much
